### ISSUE TITLE
Move `epiphany-browser` to recommends

### ISSUE THREAD

**Issue by LukeMech** [Vanilla-OS/vanilla-base-desktop#5]
Let users uninstall epiphany-browser

**Comment by kbdharun** [comment]
I agree with these changes, noticed that you created a fork. Should I add this to my existing PR to prevent conflicts. Or will you add it?

**Comment by LukeMech** [comment]
You should add it, I decided to delete fork to not break anything by mistake :) Thanks

**Comment by kbdharun** [comment]
Done https://github.com/Vanilla-OS/vanilla-base-desktop/pull/2

**Comment by LukeMech** [comment]
Btw, can you also move `gnome-user-docs` to recommended? `Yelp` cannot be uninstalled without uninstalling vanilla-base-desktop, because of this dependency

**Comment by kbdharun** [comment]
> Btw, can you also move `gnome-user-docs` to recommended? `Yelp` cannot be uninstalled without uninstalling vanilla-base-desktop, because of this dependency

I wouldn't suggest it as I added our own docs/help pages for Vanilla OS components like Vanilla Control Center (where `yelp` is a hardened dependency, as it is required for the help button).

Ref (for images): https://github.com/Vanilla-OS/vanilla-control-center/pull/93, https://github.com/Vanilla-OS/vanilla-control-center/pull/87

It is intentional by design due to this exact reason. And I have proposed repackaging it in future to the default GNOME one + adding even more sections regarding Vanilla OS.
